version: '3'

services:

  nginx:
    image: nginx:1.25.4
    container_name: hackagon_nginx
    hostname: nginx
    restart: always
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
      image: ghcr.io/gurodrigues-dev/hackagon-back:v1.0.0
      container_name: hackagon_backend
      hostname: hackagon
      restart: always

      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 500M
          reservations:
            cpus: '0.8'
            memory: 200M

      ports:
      - 127.0.0.1:7878:7878

      volumes:
        - ./config/config.yaml:/app/config/config.yaml