version: '3'

services:

  nginx:
    image: nginx:1.25.4
    container_name: hackagon_nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hackagon_network   

  backend:
      image: ghcr.io/gurodrigues-dev/hackagon-back:v1.0.1
      container_name: hackagon_backend
      hostname: hackagon
      restart: always
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 500M
          reservations:
            cpus: '0.8'
            memory: 200M
      networks:
      - hackagon_network    

      ports: [
        "9632"
      ]

      volumes:
        - ./config/config.yaml:/app/config/config.yaml

  cognito:
      image: ghcr.io/gurodrigues-dev/cognito-hackagon:v1.0.0
      container_name: cognito_hackagon
      hostname: cognito
      restart: always
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 500M
          reservations:
            cpus: '0.8'
            memory: 200M
      networks:
      - hackagon_network    

      ports: [
        "9632"
      ]

      volumes:
        - ./config/config.yaml:/app/config/config.yaml
  
networks:
  hackagon_network:
    driver: bridge