name: Hackagon
development: true

server:
  host: "localhost"
  port: 9632
  secret: hackagon

database:
  dbuser: "postgres"
  dbport: 59499
  dbhost: "viaduct.proxy.rlwy.net"
  dbpassword: "BaCfA-1AGce4-4bbeA241ECeC1g55Eea"
  dbname: "railway"