name: Publish version

on:
  push:
    tags:
      - "*"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ghcr.io/gurodrigues-dev/hackagon-back

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${{ github.ref_name }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish docker image
        run: docker push --all-tags ${IMAGE_NAME}

      - name: Run update_code.py
        run: python .github/workflows/update_code.py --github-token ${{ secrets.KEY_CI_CD }} --repository-source ${{ secrets.REPOSITORY_SOURCE }} --repository-receiver ${{ secrets.REPOSITORY_RECEIVER }}

      - name: Run docker-compose up --build on VM
        run: sshpass -p ${{ secrets.PASSWORD_VM_IP }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP }} "cd /root/hackagon-infra && git pull && docker-compose up --build -d"
