name: Deploy CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main_job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ghcr.io/gurodrigues-dev/hackagon-back
      REPOSITORY_SOURCE: ${{ secrets.REPOSITORY_SOURCE }}
      REPOSITORY_RECEIVER: "gurodrigues-dev/hackagon-infra"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Create and push new tag
      run: python .github/workflows/create_new_tag.py --github-token ${{ secrets.KEY_CI_CD }} --repository ${{ secrets.REPOSITORY_SOURCE }}

    - name: Update infra, create and merge pull request
      run: python .github/workflows/update_code.py --github-token ${{ secrets.KEY_CI_CD }} --repository-source ${{ secrets.REPOSITORY_SOURCE }} --repository-receiver ${{ secrets.REPOSITORY_RECEIVER }}